"""공통 상수 정의 (DECISIONS.md C섹션 기준).

상태값·에러코드·도메인·스키마 버전을 문자열로 흩어 쓰지 말고 여기서만 관리한다.
"""

# ── 도메인 (D-12: carebase_memory 하드코딩 최소화, 화이트리스트로 관리) ──
DOMAIN_CAREBASE = "carebase_memory"
ALLOWED_DOMAINS = {DOMAIN_CAREBASE}

# ── 스키마 버전 ──
SCHEMA_VERSION_CAREBASE_V1 = "carebase_memory_v1"

# ── AudioRecord 상태값 ──
AUDIO_RECEIVED = "AUDIO_RECEIVED"
STT_COMPLETED = "STT_COMPLETED"
STRUCTURED = "STRUCTURED"
CONFIRMED = "CONFIRMED"
AUDIO_FAILED = "FAILED"

# ── StructuredRecord 상태값 ──
AI_TEMP = "AI_TEMP"
USER_EDITED = "USER_EDITED"
USER_CONFIRMED = "USER_CONFIRMED"
REJECTED = "REJECTED"        # D-04: 정의만, MVP 미사용
NEEDS_REVIEW = "NEEDS_REVIEW"  # D-04: 정의만, MVP 미사용

# ── STT 상태값 ──
STT_SUCCESS = "SUCCESS"
STT_FAILED_STATUS = "FAILED"

# ── STT Provider ──
PROVIDER_MOCK = "mock_stt"

# ── Risk 카테고리 (MVP 감지는 TIME_CONFUSION만) ──
RISK_REPEATED_QUESTION = "REPEATED_QUESTION"
RISK_TIME_CONFUSION = "TIME_CONFUSION"
RISK_WORD_FINDING = "WORD_FINDING"

# ── 에러 코드 ──
INVALID_DOMAIN = "INVALID_DOMAIN"
AUDIO_NOT_FOUND = "AUDIO_NOT_FOUND"
TRANSCRIPT_NOT_FOUND = "TRANSCRIPT_NOT_FOUND"
STRUCTURED_RECORD_NOT_FOUND = "STRUCTURED_RECORD_NOT_FOUND"
ALREADY_CONFIRMED = "ALREADY_CONFIRMED"
FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
STT_FAILED = "STT_FAILED"
STRUCTURE_FAILED = "STRUCTURE_FAILED"
EVIDENCE_NOT_FOUND = "EVIDENCE_NOT_FOUND"
INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"  # D-04: 정의만
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
